"""Add billing_completed and work_completed to BOQ

Revision ID: 3ba6edcde87b
Revises: 
Create Date: 2025-05-21 10:42:20.671328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from app.models.boq import BOQItem

# revision identifiers, used by Alembic.
revision: str = '3ba6edcde87b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boqs', sa.Column('billing_completed', sa.String(length=255), nullable=True, server_default=""))
    op.add_column('boqs', sa.Column('work_completed', sa.String(length=255), nullable=True, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boqs', 'billing_completed')
    op.drop_column('boqs', 'work_completed')
    # ### end Alembic commands ###
